---
exclude_paths:
  - ".github/**"
  - "calculate_anything/appdirs.py"
  - "data/**"
  - "docs/**"
  - "misc/**"
  - "requirements/**"
  - "test/**"
  - "__init__.py"
  - ".coveragerc"
  - "codecov.yml"
  - "main.py"
  - "manifest.json"
  - "pytest.ini"
  - "README.md"
  - "versions.json"
