name: Benchmark
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]
jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache
        python-version: [ '3.9' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
      # Load pip cache
        with:
          path: ${{ matrix.path }}/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements/*requirements.txt') }}
          restore-keys: |
           ${{ runner.os }}-pip-${{ matrix.python-version }}
      # Setup python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/dev-requirements.txt
        # Run benchmark
      - name: Benchmark with pytest
        run: |
          pytest test/benchmark/* --benchmark-json benchmark-${{ runner.os }}-${{ matrix.python-version }}.json
        # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v2
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-benchmark-${{ matrix.python-version }}
          restore-keys: |
           ${{ runner.os }}-benchmark-${{ matrix.python-version }}
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'pytest'
          output-file-path: benchmark-${{ runner.os }}-${{ matrix.python-version }}.json
          external-data-json-path: ${{ matrix.path }}/benchmark-${{ runner.os }}-${{ matrix.python-version }}.json
          fail-on-alert: true
